<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply for This Plan</name>
   <tag></tag>
   <elementGuidId>3f971866-c6a5-4163-bd4e-8a82672eef0f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plan-details-primary-apply</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>{&quot;census&quot;:{&quot;isCanonical&quot;:false,&quot;dentalIsCanonical&quot;:true,&quot;oneTimePaymentSelected&quot;:false,&quot;stIndeterminateContractLength&quot;:true,&quot;planYear&quot;:2015,&quot;member&quot;:[{&quot;role&quot;:&quot;P&quot;,&quot;age&quot;:31,&quot;smoker&quot;:false,&quot;gender&quot;:&quot;M&quot;,&quot;dob&quot;:&quot;1987-04-04&quot;,&quot;eligible&quot;:true}],&quot;dentalEffective&quot;:&quot;2019-01-01T05:00:00.000Z&quot;,&quot;effective&quot;:&quot;2018-12-30T05:00:00.000Z&quot;,&quot;maxEffectiveEnd&quot;:null,&quot;location&quot;:{&quot;zip&quot;:&quot;60602&quot;,&quot;state&quot;:&quot;IL&quot;,&quot;county&quot;:&quot;Cook&quot;,&quot;fips&quot;:&quot;17031&quot;,&quot;_id&quot;:{&quot;_bsontype&quot;:&quot;ObjectID&quot;,&quot;id&quot;:{&quot;type&quot;:&quot;Buffer&quot;,&quot;data&quot;:[90,204,84,123,200,52,135,60,78,141,255,222]}},&quot;fullCodeList&quot;:[&quot;14141&quot;],&quot;code&quot;:&quot;14141&quot;,&quot;maRegionCode&quot;:&quot;14&quot;,&quot;pdpRegionCode&quot;:&quot;17&quot;,&quot;ifpRegionCode&quot;:&quot;1&quot;,&quot;defaultedCounty&quot;:false,&quot;city&quot;:&quot;Chicago&quot;,&quot;stateName&quot;:&quot;Illinois&quot;},&quot;effectiveEnd&quot;:&quot;2019-06-28T04:00:00.000Z&quot;},&quot;plan&quot;:{&quot;_id&quot;:&quot;5c12930a3fc2e71018f285c4&quot;,&quot;coinsurance&quot;:20,&quot;primaryDoctorVisit&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;$30 Copayment per visit per Covered Person not to exceed a maximum of 3 Copayments per Covered Person. Eligible Expenses and benefits are not subject to the Plan Deductible or Coinsurance. Office Visits in excess of the maximum number of Copayments will be subject to the Plan Deductible and Coinsurance.&quot;},&quot;specialist&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;$30 Copayment per visit per Covered Person not to exceed a maximum of 3 Copayments per Covered Person. Eligible Expenses and benefits are not subject to the Plan Deductible or Coinsurance. Office Visits in excess of the maximum number of Copayments will be subject to the Plan Deductible and Coinsurance.&quot;},&quot;periodicExam&quot;:{&quot;amount&quot;:50,&quot;message&quot;:&quot;Covered - member pays $50 copay, benefit is not subject to deductible or coinsurance.&quot;},&quot;obGynExam&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;wellBaby&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;chiropractic&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;mentalHealth&quot;:{&quot;amount&quot;:100,&quot;message&quot;:&quot;Inpatient: $100 per day, 31 day maximum per Covered Person per Coverage Period. Outpatient: $50 per visit, 10 visits per Covered Person per Coverage Period&quot;},&quot;rxGeneric&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;rxBrand&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;rxNonFormulary&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;rxDeductible&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;labXray&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;emergency&quot;:{&quot;amount&quot;:24,&quot;message&quot;:&quot;Emergency Room (This includes the emergency room physician charge, 24 hours surveillance and all miscellaneous medical charges) The benefit payable for each emergency room visit, including professional and facility services, will not exceed $250 per visit.&quot;},&quot;outpatient&quot;:{&quot;amount&quot;:1,&quot;message&quot;:&quot;Facility charges up to a max of $1,250 per day; $5,000 Surgeon and $1,000 Assistant Surgeon limitations apply&quot;},&quot;hospitalization&quot;:{&quot;amount&quot;:1,&quot;message&quot;:&quot;Average Standard Room Rate: $1,000 per day. Hospital ICU: $1,250 per day&quot;},&quot;preAndPostNatal&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;deliveryHospital&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;familyMoopType&quot;:&quot;M&quot;,&quot;maxOOPLimits&quot;:3,&quot;familyDeductibleType&quot;:&quot;M&quot;,&quot;maxDeductibleLimits&quot;:3,&quot;deductibleTotalingType&quot;:&quot;&quot;,&quot;additionalCoverages&quot;:[],&quot;carrierId&quot;:&quot;lifeshield&quot;,&quot;planSubType&quot;:&quot;lite&quot;,&quot;planName&quot;:&quot;LifeShield Flex 5000/20/9000/750000&quot;,&quot;planType&quot;:&quot;PPO&quot;,&quot;wellBabyCare&quot;:false,&quot;periodicHealthExam&quot;:false,&quot;periodicObGyn&quot;:false,&quot;maternity&quot;:false,&quot;primaryCarePhysicianRequired&quot;:false,&quot;referralsRequired&quot;:false,&quot;primaryCareServiceBenefit&quot;:false,&quot;primaryCareBenefitURL&quot;:&quot;&quot;,&quot;oonCoverage&quot;:true,&quot;internationalCoverage&quot;:&quot;No&quot;,&quot;internationalCoverageDetail&quot;:&quot;&quot;,&quot;internationalCoverageURL&quot;:&quot;&quot;,&quot;officeVisit&quot;:&quot;&quot;,&quot;moopIncludesDeductible&quot;:true,&quot;familyMoopIncludesDeductible&quot;:false,&quot;waitingPeriodForIllnesses&quot;:5,&quot;__v&quot;:0,&quot;planId&quot;:&quot;lifeshield-flex-il-5000-20-9000-750000&quot;,&quot;providerInfo&quot;:{&quot;_id&quot;:&quot;58b627a6de34940400e01519&quot;,&quot;updated&quot;:&quot;2017-07-06T05:36:33.093Z&quot;,&quot;uri&quot;:&quot;lifeshield-4icyj&quot;,&quot;lastUpdatedBy&quot;:&quot;Beck Lin&quot;,&quot;hpId&quot;:&quot;lifeshield&quot;,&quot;displayName&quot;:&quot;LifeShield&quot;,&quot;logoFile&quot;:&quot;https://stratos.healthpocket.com/lifeshield-8026365c4d6c5ebcef0cc620b6223217.png&quot;,&quot;url&quot;:&quot;&quot;,&quot;__v&quot;:0,&quot;created&quot;:&quot;2017-03-01T01:45:10.273Z&quot;,&quot;sourceNames&quot;:[&quot;LifeShield&quot;],&quot;companyName&quot;:[{&quot;name&quot;:&quot;LifeShield National Insurance Co.&quot;,&quot;_id&quot;:&quot;595dcc61908b4800048314d6&quot;,&quot;state&quot;:&quot;ALL&quot;}],&quot;productLines&quot;:[&quot;ST&quot;],&quot;states&quot;:[]},&quot;breakdown&quot;:{&quot;applicant&quot;:42.79,&quot;spouse&quot;:0,&quot;children&quot;:0,&quot;tax&quot;:1,&quot;baseRate&quot;:42.79,&quot;fees&quot;:{&quot;medsense&quot;:{&quot;kind&quot;:&quot;R&quot;,&quot;_id&quot;:&quot;5c12930a3fc2e71018f28581&quot;,&quot;id&quot;:&quot;medsense&quot;,&quot;amount&quot;:19.99}},&quot;monthlyCost&quot;:62.78,&quot;initialCost&quot;:62.78,&quot;totalRecurringFee&quot;:19.99},&quot;deductible&quot;:5000,&quot;externalPlanId&quot;:137,&quot;coinsuranceLimit&quot;:20000,&quot;companyName&quot;:&quot;LifeShield National Insurance Co.&quot;,&quot;lifetimeMax&quot;:750000,&quot;moop&quot;:9000,&quot;outOfPocketMax&quot;:9000,&quot;maxDurationMonths&quot;:6,&quot;extended&quot;:false,&quot;daily&quot;:false,&quot;extendedPlanId&quot;:&quot;lifeshield-flex-il-5000-20-9000-750000-extended&quot;,&quot;consecutiveDurationMonths&quot;:6,&quot;preXFactor&quot;:1.475,&quot;consecutiveOption&quot;:1,&quot;familyDeductible&quot;:15000,&quot;familyMoop&quot;:27000,&quot;minEffectiveDate&quot;:&quot;2018-12-30T05:00:00.000Z&quot;,&quot;effectiveEnd&quot;:&quot;2019-06-29T04:00:00.000Z&quot;,&quot;maxEffectiveEnd&quot;:&quot;2019-06-29T04:00:00.000Z&quot;,&quot;coverageDurationPeriod&quot;:6,&quot;logoFile&quot;:&quot;https://stratos.healthpocket.com/lifeshield-8026365c4d6c5ebcef0cc620b6223217.png&quot;,&quot;hasFees&quot;:true},&quot;productLine&quot;:&quot;Short Term&quot;,&quot;selectedConsecutive&quot;:false}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-apply btn btn-primary btn-lg apply-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/term-health-insurance/apply/lifeshield-flex-il-5000-20-9000-750000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply for This Plan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-details-primary-apply&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//a[@id='plan-details-primary-apply']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//section[@id='js-plan-summary']/div/div[3]/div/div/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'Apply for This Plan')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ fees'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LifeShield Flex 5000/20/9000/750000'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Plan'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Plan Brochure'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, '/term-health-insurance/apply/lifeshield-flex-il-5000-20-9000-750000')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/div/div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
