<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form</name>
   <tag></tag>
   <elementGuidId>245d23b7-3b24-4053-b28b-56d4c384e63c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form</value>
   </webElementProperties>
</WebElementEntity>
