<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>stm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3a84ae2e-51cc-4f76-aa9c-4ba9d9d3a4c8</testSuiteGuid>
   <testCaseLink>
      <guid>46691638-2c9d-496a-a422-3e6363156942</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/AdvantHealth</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0df5e54c-4ed9-443c-a562-799867a9387c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/Aspen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7edea1c1-5025-4297-b7a3-5c8505d43043</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/Companion</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b702a8a7-b9a3-4497-9a99-eefd68672019</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/Everest Prime</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>65096ff1-a9aa-46ea-be59-4126540b01fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/Everest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>062f62ba-9106-44d0-9da1-8359eb4a0b12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/LifeShield</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8337adbb-f040-4173-98b9-c603d302eebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeccc1d-a1cd-4e5e-96ea-d7cf567f777c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f33728-f684-4c4d-8b8a-38d716b13e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a177220-6d58-4ef2-a0e4-ef64f2d94914</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef86dad7-46bf-48cf-a30a-78f6ccd21e81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/NationalGeneral</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2ca0ce14-ed90-4557-9289-f18a3f5059eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AHI/stm/Slaico</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7141a177-36a3-434f-97c0-6810e05d4317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9c6e43-d249-4caf-8db2-3d551811e7dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ec1771-b963-4611-82dc-9dac6b1a0061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0323b0-bf4e-44f7-a24f-d7f346c4dc4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040afb4d-b4dd-47c9-a0f1-9760d77e9f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ec7ad3-c8a6-462e-bcf6-112588cc7b70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa471c79-5ac1-4451-881f-872f09ef627e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd79c46-89de-41c0-bbc2-dd1e6b92f786</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
