<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>hic</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6a7adaa9-d433-43e1-b481-d3167125d837</testSuiteGuid>
   <testCaseLink>
      <guid>fc3c7613-9d8c-47cd-8ed4-800bdbd5f878</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/ACA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>369c7da4-0c05-4d25-b7a8-a64e3d86c467</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9455eae3-8330-4daf-bfe3-973f8b36ecee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/Cancer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d374ecd-78a2-4272-a3b0-e20fa9e26f18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc550d91-089b-4974-a03b-a19bc5ea82b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/Dental</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c478af82-206e-4651-b8a0-10978accdaf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0df42d25-f2da-4500-a243-84fabd6a5449</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/HBI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad562c51-c1b4-4457-b2e6-b80f76d9e84c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5f32291-a031-479b-a94c-164bc39fba1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/Medicare</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ddc5c1-8da6-4f59-bfd8-928669dffb92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af2934c4-633c-4e6f-8a15-1a608d93c804</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/Pet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>698655f5-7665-4105-9540-b75980258356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f26df93-56dd-443f-9f7e-98c61c74d254</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/STM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38353acb-85ab-4080-8870-5d0740ad08b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c896b27d-676e-47f5-8c16-63e78667d8d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/New/Teladoc</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d5cdb53-50d6-48e8-ae59-1e6a09c0c667</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
