<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>humana</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>72682fa9-f12d-4e08-9762-fbcab04eb4d7</testSuiteGuid>
   <testCaseLink>
      <guid>a74a4dfa-7a20-478d-b0ff-45fa12af1af6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HIC/Plan enrollment/Humana</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e861eff-cdf1-484f-a4a7-699cf19af93a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41313a9b-0ae2-4ce8-9ee9-7412ac3a06bd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
