<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>context</name>
   <tag></tag>
   <elementGuidId>c00e4105-0fce-4456-a38a-52786f5d46b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//pre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//pre</value>
   </webElementProperties>
</WebElementEntity>
