<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>member-P-1-no-smoker</name>
   <tag></tag>
   <elementGuidId>87623724-c52a-45a5-b528-524845de0601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='member-P-1-no-smoker']/following::label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='member-P-1-no-smoker']/following::label</value>
   </webElementProperties>
</WebElementEntity>
