<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>mobileSanity</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5c2b6e37-c156-46ca-80a7-838b939358f0</testSuiteGuid>
   <testCaseLink>
      <guid>447ba290-aa54-4686-9aba-01a416f0f6fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Slaico</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>87043a79-8edb-43cd-afe8-be8a44c7612b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Level 1/Lifeshield</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7141a177-36a3-434f-97c0-6810e05d4317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9c6e43-d249-4caf-8db2-3d551811e7dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ec1771-b963-4611-82dc-9dac6b1a0061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0323b0-bf4e-44f7-a24f-d7f346c4dc4d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
