<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>stm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>denis.yu@suryani.cn;sofee.yu@suryani.cn;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>47a40322-b0ca-4d90-8fd6-8937a52575b1</testSuiteGuid>
   <testCaseLink>
      <guid>2936922f-f754-4dd1-b936-525d33728c22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Slaico</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7141a177-36a3-434f-97c0-6810e05d4317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9c6e43-d249-4caf-8db2-3d551811e7dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ec1771-b963-4611-82dc-9dac6b1a0061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0323b0-bf4e-44f7-a24f-d7f346c4dc4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040afb4d-b4dd-47c9-a0f1-9760d77e9f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ec7ad3-c8a6-462e-bcf6-112588cc7b70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa471c79-5ac1-4451-881f-872f09ef627e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd79c46-89de-41c0-bbc2-dd1e6b92f786</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46d45f0b-a6e7-448c-9c89-a71aa091b757</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/AdvantHealth</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1a03245c-5d1b-403d-80b7-b0846f788c8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Companion</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1bf14ac0-f992-4b7d-94d2-c9a8a59f46b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Everest Prime</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2ea47660-6f90-435e-8c2b-bcac933eb325</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/LifeShield</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8337adbb-f040-4173-98b9-c603d302eebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeccc1d-a1cd-4e5e-96ea-d7cf567f777c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f33728-f684-4c4d-8b8a-38d716b13e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a177220-6d58-4ef2-a0e4-ef64f2d94914</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efd05439-eeea-4f52-bd4f-af23fbdb1292</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/NationalGeneral</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>09cb3114-bc59-49bb-a343-cf6d4c2043e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/UnitedHealthOne</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
