<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>stm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-02-19T16:29:24</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>47a40322-b0ca-4d90-8fd6-8937a52575b1</testSuiteGuid>
   <testCaseLink>
      <guid>1208024c-7ac2-419c-b2c1-56339bd63507</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/AdvantHealth Plan 1</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a9dfc0fc-8a68-49be-a57b-210acab5b5f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Companion</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7a0bdf03-4430-462d-8a67-2b3fe0b11851</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Everest Prime</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8416a35c-1e76-4834-83b1-63c0302b81db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/LifeShield</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8337adbb-f040-4173-98b9-c603d302eebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeccc1d-a1cd-4e5e-96ea-d7cf567f777c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f33728-f684-4c4d-8b8a-38d716b13e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a177220-6d58-4ef2-a0e4-ef64f2d94914</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33a19647-5c4a-4a5a-bcf8-76e134a85175</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/NationalGeneral</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>84a849a9-06c1-43da-99f7-a7b21a3284f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Slaico</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7141a177-36a3-434f-97c0-6810e05d4317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9c6e43-d249-4caf-8db2-3d551811e7dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ec1771-b963-4611-82dc-9dac6b1a0061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0323b0-bf4e-44f7-a24f-d7f346c4dc4d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
