<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>stm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-07-18T17:34:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e853617b-7f85-40a5-99e7-ad726a8a4d53</testSuiteGuid>
   <testCaseLink>
      <guid>0ad80c73-d89d-4919-b4b3-0d3fa7867f36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Slaico</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7141a177-36a3-434f-97c0-6810e05d4317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9c6e43-d249-4caf-8db2-3d551811e7dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ec1771-b963-4611-82dc-9dac6b1a0061</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0323b0-bf4e-44f7-a24f-d7f346c4dc4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040afb4d-b4dd-47c9-a0f1-9760d77e9f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ec7ad3-c8a6-462e-bcf6-112588cc7b70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa471c79-5ac1-4451-881f-872f09ef627e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd79c46-89de-41c0-bbc2-dd1e6b92f786</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33ab757e-d7d0-43e4-9d45-3900f01d343a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/AdvantHealth</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f17b647e-d849-4454-acdd-3044194b04a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Companion</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b8e4d67a-4269-48b6-a6ce-50176929a209</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Everest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a67b6d5f-2094-458f-b89a-c0be86dbce6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/Everest Prime</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f8dae1c7-1bb6-4a6b-b869-79ea4ecf2cf0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/LifeShield</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8337adbb-f040-4173-98b9-c603d302eebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeccc1d-a1cd-4e5e-96ea-d7cf567f777c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f33728-f684-4c4d-8b8a-38d716b13e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a177220-6d58-4ef2-a0e4-ef64f2d94914</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fa11fe9-5d19-46e6-b02b-56d06380b41e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobileWeb/stm/NationalGeneral</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
