<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zip</name>
   <tag></tag>
   <elementGuidId>538f9e3b-704f-46d7-bfcc-7363a1603d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-zip[@name='ZipCode']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-zip[@name='ZipCode']/input</value>
   </webElementProperties>
</WebElementEntity>
