<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start Secure Application</name>
   <tag></tag>
   <elementGuidId>5b4803b8-f29d-4e6b-94dc-d75c0f38a7db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;applyButton&quot;)[count(. | //a[@id = 'applyButton' and (text() = ' Start Secure Application' or . = ' Start Secure Application')]) = count(//a[@id = 'applyButton' and (text() = ' Start Secure Application' or . = ' Start Secure Application')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/term-health-insurance/enroll/slaico-il-plan-2-10000-30-20000-1000000?riders%5B%5D=teladoc-rider</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applyButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-apply-button btn js-apply-button h-optimize__original</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>{&quot;census&quot;:{&quot;isCanonical&quot;:false,&quot;dentalIsCanonical&quot;:true,&quot;oneTimePaymentSelected&quot;:false,&quot;stIndeterminateContractLength&quot;:true,&quot;planYear&quot;:2015,&quot;member&quot;:[{&quot;role&quot;:&quot;P&quot;,&quot;age&quot;:31,&quot;smoker&quot;:false,&quot;gender&quot;:&quot;M&quot;,&quot;dob&quot;:&quot;03/03/1987&quot;,&quot;eligible&quot;:true}],&quot;dentalEffective&quot;:&quot;2019-01-01T05:00:00.000Z&quot;,&quot;maxEffectiveEnd&quot;:null,&quot;location&quot;:{&quot;zip&quot;:&quot;60602&quot;,&quot;state&quot;:&quot;IL&quot;,&quot;county&quot;:&quot;Cook&quot;,&quot;fips&quot;:&quot;17031&quot;,&quot;_id&quot;:{&quot;_bsontype&quot;:&quot;ObjectID&quot;,&quot;id&quot;:{&quot;type&quot;:&quot;Buffer&quot;,&quot;data&quot;:[90,204,84,123,200,52,135,60,78,141,255,222]}},&quot;fullCodeList&quot;:[&quot;14141&quot;],&quot;code&quot;:&quot;14141&quot;,&quot;maRegionCode&quot;:&quot;14&quot;,&quot;pdpRegionCode&quot;:&quot;17&quot;,&quot;ifpRegionCode&quot;:&quot;1&quot;,&quot;defaultedCounty&quot;:false,&quot;city&quot;:&quot;Chicago&quot;,&quot;stateName&quot;:&quot;Illinois&quot;},&quot;quotedPrice&quot;:81.05},&quot;productLine&quot;:&quot;Short Term&quot;,&quot;plan&quot;:{&quot;_id&quot;:&quot;5c22dc9443ac35007b98876f&quot;,&quot;oonCoverageDetail&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;Subject to a %d%% coinsurance reduction.&quot;},&quot;coinsurance&quot;:30,&quot;primaryDoctorVisit&quot;:{&quot;amount&quot;:50,&quot;message&quot;:&quot;During your coverage period, you can make an unlimited number of Doctor Office and Urgent Care visits for a predictable $50 dollar copay per visit, not subject to deductible or coinsurance, up to a maximum benefit of $2000 per coverage period.&quot;},&quot;specialist&quot;:{&quot;amount&quot;:50,&quot;message&quot;:&quot;During your coverage period, you can make an unlimited number of Doctor Office and Urgent Care visits for a predictable $50 dollar copay per visit, not subject to deductible or coinsurance, up to a maximum benefit of $2000 per coverage period.&quot;},&quot;periodicExam&quot;:{&quot;amount&quot;:75,&quot;message&quot;:&quot;No charge up to $75 per Coverage Period.  The benefit payable per Coverage Period is limited to $75. Charges for preventive/wellness care are not subject to Plan Deductible or Coinsurance Percentage.&quot;},&quot;obGynExam&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;N/A&quot;},&quot;wellBaby&quot;:{&quot;amount&quot;:75,&quot;message&quot;:&quot;No charge up to $75 per Coverage Period.  The benefit payable per Coverage Period is limited to $75. Charges for preventive/wellness care are not subject to Plan Deductible or Coinsurance Percentage.&quot;},&quot;chiropractic&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Covered except: spinal manipulation or adjustment&quot;},&quot;mentalHealth&quot;:{&quot;amount&quot;:100,&quot;message&quot;:&quot;Inpatient: $100 maximum per day, 31 day maximum per Coverage Period; Outpatient: $50 maximum per visit, 10 visit maximum per Coverage Period.&quot;},&quot;rxGeneric&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Inpatient: Coinsurance + Deductible\rOutpatient: Not Covered, discount card provided&quot;},&quot;rxBrand&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Inpatient: Coinsurance + Deductible\rOutpatient: Not Covered, discount card provided&quot;},&quot;rxNonFormulary&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Inpatient: Coinsurance + Deductible\rOutpatient: Not Covered, discount card provided&quot;},&quot;rxDeductible&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;&quot;},&quot;labXray&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;%d%% Coinsurance after deductible&quot;},&quot;emergency&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;%d%% Coinsurance after deductible&quot;},&quot;outpatient&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;%d%% Coinsurance after deductible&quot;},&quot;hospitalization&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;%d%% Coinsurance after deductible&quot;},&quot;preAndPostNatal&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;deliveryHospital&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;urgentCare&quot;:{&quot;amount&quot;:50,&quot;message&quot;:&quot;During your coverage period, you can make an unlimited number of Doctor Office and Urgent Care visits for a predictable $50 dollar copay per visit, not subject to deductible or coinsurance, up to a maximum benefit of $2000 per coverage period.&quot;},&quot;familyMoopType&quot;:&quot;All Members&quot;,&quot;maxOOPLimits&quot;:0,&quot;familyDeductibleType&quot;:&quot;M&quot;,&quot;maxDeductibleLimits&quot;:3,&quot;deductibleTotalingType&quot;:&quot;S&quot;,&quot;additionalCoverages&quot;:[],&quot;carrierId&quot;:&quot;slaico&quot;,&quot;planSubType&quot;:&quot;plan2&quot;,&quot;wellBabyCare&quot;:false,&quot;periodicHealthExam&quot;:true,&quot;periodicObGyn&quot;:false,&quot;maternity&quot;:false,&quot;prescriptionDrug&quot;:true,&quot;moop&quot;:16000,&quot;moopIncludesDeductible&quot;:true,&quot;familyMoop&quot;:48000,&quot;familyMoopIncludesDeductible&quot;:false,&quot;primaryCarePhysicianRequired&quot;:false,&quot;referralsRequired&quot;:false,&quot;primaryCareServiceBenefit&quot;:true,&quot;primaryCareBenefitURL&quot;:&quot;&quot;,&quot;oonCoverage&quot;:true,&quot;internationalCoverage&quot;:&quot;None&quot;,&quot;internationalCoverageDetail&quot;:&quot;Charges for medical care while traveling in a foreign country. The treatment must be rendered for an Injury or the sudden and unexpected onset of a Sickness requiring immediate medical attention and must be provided within the first 90 days of the Covered Person's trip outside the United States. Benefits payable are limited to $25,000 per Coverage Period.&quot;,&quot;planType&quot;:&quot;PPO&quot;,&quot;officeVisit&quot;:&quot;50&quot;,&quot;network&quot;:&quot;Multiplan PHCS&quot;,&quot;waitingPeriodForIllnesses&quot;:3,&quot;__v&quot;:0,&quot;planId&quot;:&quot;slaico-il-plan-2-10000-30-20000-1000000&quot;,&quot;providerInfo&quot;:{&quot;_id&quot;:&quot;565f8d1b9f1190030096ee42&quot;,&quot;updated&quot;:&quot;2018-08-23T05:55:27.603Z&quot;,&quot;uri&quot;:&quot;standard-life-0kpac&quot;,&quot;lastUpdatedBy&quot;:&quot; &quot;,&quot;hpId&quot;:&quot;slaico&quot;,&quot;displayName&quot;:&quot;Standard Life&quot;,&quot;logoFile&quot;:&quot;https://stratos.healthpocket.com/slaico-e0c9e5e67aa59ce1109d60047c478049.png&quot;,&quot;url&quot;:&quot;&quot;,&quot;__v&quot;:1,&quot;created&quot;:&quot;2015-12-03T00:30:19.929Z&quot;,&quot;sourceNames&quot;:[&quot;slaico&quot;,&quot;Standard Life&quot;],&quot;companyName&quot;:[{&quot;name&quot;:&quot;Standard Life and Accident Insurance Company&quot;,&quot;_id&quot;:&quot;595dcc61908b4800048314d8&quot;,&quot;state&quot;:&quot;ALL&quot;}],&quot;productLines&quot;:[&quot;ST&quot;],&quot;states&quot;:[]},&quot;breakdown&quot;:{&quot;applicant&quot;:61.06,&quot;spouse&quot;:0,&quot;children&quot;:0,&quot;tax&quot;:1,&quot;baseRate&quot;:61.06,&quot;fees&quot;:{&quot;medsense&quot;:{&quot;kind&quot;:&quot;R&quot;,&quot;id&quot;:&quot;medsense&quot;,&quot;amount&quot;:19.99,&quot;displayName&quot;:&quot;MSGA Association Dues&quot;,&quot;description&quot;:&quot;This plan is only available to members of the Med-Sense Guaranteed Association and the MSGA Association Dues is the monthly membership dues.  Through your membership in MSGA, you will enjoy discounts on a variety of Health, Travel, Consumer and Business services.   For more information regarding MSGA association and its benefits, please visit www.medsensemembers.com&quot;}},&quot;monthlyCost&quot;:81.05,&quot;initialCost&quot;:81.05},&quot;deductible&quot;:10000,&quot;externalPlanId&quot;:106,&quot;coinsuranceLimit&quot;:20000,&quot;planName&quot;:&quot;Standard Life Select STM Plan 2 10000/30/1M&quot;,&quot;companyName&quot;:&quot;Standard Life and Accident Insurance Company&quot;,&quot;lifetimeMax&quot;:1000000,&quot;outOfPocketMax&quot;:16000,&quot;maxDurationMonths&quot;:6,&quot;extended&quot;:false,&quot;daily&quot;:false,&quot;extendedPlanId&quot;:&quot;slaico-il-plan-2-10000-30-20000-1000000-extended&quot;,&quot;consecutiveDurationMonths&quot;:6,&quot;consecutiveOption&quot;:1,&quot;familyDeductible&quot;:30000,&quot;minEffectiveDate&quot;:&quot;2019-01-01T05:00:00.000Z&quot;,&quot;effectiveEnd&quot;:&quot;2019-06-30T04:00:00.000Z&quot;,&quot;maxEffectiveEnd&quot;:&quot;2019-06-30T04:00:00.000Z&quot;,&quot;coverageDurationPeriod&quot;:6,&quot;logoFile&quot;:&quot;https://stratos.healthpocket.com/slaico-e0c9e5e67aa59ce1109d60047c478049.png&quot;,&quot;consecutivePoliciesAvailable&quot;:false},&quot;selectedConsecutive&quot;:false}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Start Secure Application</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyButton&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//a[@id='applyButton']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='applyCta']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$91.00'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Total'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Secure Application'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, '/term-health-insurance/enroll/slaico-il-plan-2-10000-30-20000-1000000?riders%5B%5D=teladoc-rider')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
