<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>compare_checkbox_1</name>
   <tag></tag>
   <elementGuidId>3f62bc41-8ae9-4d60-bcd5-70d2c6c62e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//label[text()='Compare'])[1]/preceding::input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label[text()='Compare'])[1]/preceding::input[1]</value>
   </webElementProperties>
</WebElementEntity>
