<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drug_i-frequency</name>
   <tag></tag>
   <elementGuidId>ef7bb811-68c5-4ea1-8c3d-df06f7ab9196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='i-frequency']/following::div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='i-frequency']/following::div/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
