<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>your_current_plan_company_input</name>
   <tag></tag>
   <elementGuidId>d4dfab9d-a876-4f0f-815d-7f256979f972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input)[1]</value>
   </webElementProperties>
</WebElementEntity>
